default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: secret123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: web_service_development

production:
 <<: *default
 database: web_service_production
 pool: 5
 timeout: 5000
 username: web_service
 password: secret123
 host: '3.134.253.125'
 socket: '/var/run/mysqld/mysqld.sock'

test:
  <<: *default
  database: web_api_template_test
